---

- name: Include ./set_dev_machine_facts.yml tasks
  import_tasks: ./set_dev_machine_facts.yml

- name: Install asdf
  tags: [install_asdf]
  import_tasks: ./install_asdf.yml

- name: Install chezmoi
  tags: [install_chezmoi]
  import_tasks: ./install_chezmoi.yml

# - name: Install neovim's dependencies
#   tags: [install_neovim_deps, install_neovim]
#   import_tasks: ./install_neovim_deps.yml

  tags: [install_neovim]
  tags: [install_neovim]
  import_tasks: ./install_neovim.yml

# - name: Install nushell
#   tags: [install_nushell]
#   import_tasks: ./install_nushell.yml
